server:
  port: 8002
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: zjl
        instance-id: instance
        health-check-path: /health
        datacenters: