server:
  port: 8080
  servlet:
    context-path: /valid
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

