server:
  port: 80
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
rpc:
  service:
    bserver1:
       ip: "123"
       api: "api"
    bserver2:
       ip: "123"
       api: "api"

