server:
  port: 80
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

