spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 80
        max-wait: 5
        max-idle: 8
        min-idle: 0
    timeout: 2000
